athena:
  outputs:
    default:
      type: athena
      s3_staging_dir: s3://aws-athena-query-results-us-west-2-472220033535/dbt/
      region_name: us-west-2
      schema: dbt
      database: awsdatacatalog
      threads: 4
